import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve, sep } from 'node:path';
import type { AddressInfo } from 'node:net';
import { config } from '../gateway/config.js';
import { Store } from '../data/storage/database.js';
import { initAuth } from '../security/auth/schema.js';
import { AuthService } from '../security/auth/service.js';
import { hashPassword, totpCode } from '../security/auth/crypto.js';
import { createApp } from '../gateway/app.js';

test('native login requires setup before chat, then persists and streams the authenticated conversation', async t => {
  const original = { ...config };
  const directory = await mkdtemp(join(tmpdir(), 'lumina-auth-test-'));
  Object.assign(config, { AUTH_MODE: 'native', NODE_ENV: 'test', LUMINA_ENCRYPTION_KEY: '11'.repeat(32), DATA_DIR: directory, LLM_MODEL: '', EMBEDDING_MODEL: '', KNOWLEDGE_ENABLED: false });
  const store = new Store('', directory);
  await store.init(); await initAuth(store);
  const auth = new AuthService(store);
  await auth.createUser({ code: 'TE000001', email: 'test@example.invalid', name: 'Test', passwordHash: await hashPassword('Initial123!'), scopes: ['geral'], mustChange: 1 });
  const { app, ingestion, webImports } = createApp(store);
  const server = app.listen(0, '127.0.0.1');
  await new Promise<void>(resolve => server.once('listening', resolve));
  t.after(async () => {
    await new Promise<void>(resolve => server.close(() => resolve()));
    await webImports.close(); await ingestion.idle(); await store.close();
    Object.assign(config, original);
    const target = resolve(directory);
    if (target.startsWith(resolve(tmpdir()) + sep) && target.includes('lumina-auth-test-')) await rm(target, { recursive: true, force: true });
  });
  const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}/api`;
  let cookie = '';
  const request = async (path: string, body?: unknown, stream = false) => {
    const response = await fetch(base + path, { method: body ? 'POST' : 'GET', headers: { 'Content-Type': 'application/json', 'X-Lumina-Request': '1', Cookie: cookie, ...(stream ? { Accept: 'text/event-stream' } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
    const setCookie = response.headers.get('set-cookie');
    if (setCookie) cookie = setCookie.split(';')[0];
    return response;
  };
  assert.equal((await request('/me')).status, 401);
  assert.equal((await request('/auth/login', { identifier: 'TE000001', password: 'Initial123!' })).status, 200);
  assert.equal((await request('/me')).status, 200);
  assert.equal((await request('/domains')).status, 403);
  const weak = await request('/auth/password', { current_password: 'Initial123!', new_password: 'weak' });
  assert.equal(weak.status, 400);
  assert.match((await weak.json()).error, /maiúscula/);
  assert.equal((await request('/auth/password', { current_password: 'Initial123!', new_password: 'Changed123!' })).status, 200);
  const setup = await (await request('/auth/2fa/setup', {})).json();
  assert.equal((await request('/auth/2fa/enable', { code: totpCode(setup.secret) })).status, 200);
  assert.equal((await request('/domains')).status, 200);
  const conversationId = crypto.randomUUID();
  const chat = await request('/chat', { question: 'Olá', domain: 'geral', conversationId }, true);
  assert.equal(chat.status, 200);
  const events = await chat.text();
  assert.match(events, /event: result/);
  assert.doesNotMatch(events, /event: error/);
  const runs = await (await request('/runs?domain=geral')).json();
  assert.equal(runs[0].conversationId, conversationId);
  assert.equal(runs[0].question, 'Olá');
  assert.equal((await request('/auth/logout', {})).status, 200);
  assert.equal((await request('/me')).status, 401);
  const challenge = await request('/auth/login', { identifier: 'TE000001', password: 'Changed123!' });
  assert.equal((await challenge.json()).requires_2fa, true);
  assert.equal((await request('/me')).status, 401);
});
